### ISSUE TITLE
Updating!

### ISSUE THREAD

**Issue by Stimulation** [denniss17/dsTitles#5]
Hey do you plan on updating this as there is an issue on 1.9! 

Would you mind if I updated the plugin?

**Comment by dennisschroer** [comment]
Can you provide more information about the issue on 1.9?

Anyway, feel free to make improvements and create a PR ;)

**Comment by Stimulation** [comment]
[12:20:47] [Server thread/INFO]: [dsTitle] Enabling dsTitle v1.5.0
[12:20:47] [Server thread/ERROR]: Error occurred while enabling dsTitle v1.5.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
    at denniss17.dsTitle.TeamManager.reloadTags(TeamManager.java:113) ~[?:?]
    at denniss17.dsTitle.DSTitle.onEnable(DSTitle.java:44) ~[?:?]
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.loadPlugin(CraftServer.java:361) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at org.bukkit.craftbukkit.v1_9_R1.CraftServer.enablePlugins(CraftServer.java:321) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at net.minecraft.server.v1_9_R1.MinecraftServer.t(MinecraftServer.java:411) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at net.minecraft.server.v1_9_R1.MinecraftServer.l(MinecraftServer.java:376) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at net.minecraft.server.v1_9_R1.MinecraftServer.a(MinecraftServer.java:331) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at net.minecraft.server.v1_9_R1.DedicatedServer.init(DedicatedServer.java:269) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at net.minecraft.server.v1_9_R1.MinecraftServer.run(MinecraftServer.java:527) [spigot-1.9.jar:git-Spigot-104c8c8-e43b278]
    at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]

**Comment by Stimulation** [comment]
Soo will you release a 1.9? or can I?

With full credit!

**Comment by DrkMatr1984** [comment]
I've already updated this plugin, and fixed several bugs, plus have added DeluxeChat/PlaceHolderAPI support. Check out my repo : 
https://github.com/DrkMatr1984/dsTitles

**Comment by Stimulation** [comment]
Ohh good stuff, I've updated a personal copy! Think ill use yours as thats a good idea with the placeholders :)

**Comment by DrkMatr1984** [comment]
Thanks :) I'm planning on adding mvdwPlaceHolderAPI support soon also, so we can use the titles in TitleAdvanced, Featherboard, Etc. I have a pull request in to Dennis for the updates but he has yet to take my pull. I'll make sure to update the release jar when I add the mvdwPlaceHolderAPI support.

**Comment by dennisschroer** [comment]
Thanks for your contribution. Is this issue fixed in https://github.com/denniss17/dsTitles/pull/4?

Unfortunately I do not have much time for this project (and minecraft) anymore, which is the reason why I am responding so lately. I will see if I can merge the PR somewhere in the next days and update the plugin.

**Comment by DrkMatr1984** [comment]
Oh yeah, that was fixed a while ago :P As deluxechat dropped support for registering placeholders directly into their plugin, I just dropped DeluxeChat support completely eventually. Pretty much every plugin is using PlaceholderAPI by clip now or mvdwPlaceholderAPI which dsTitles also has support for now.
